{
  "formatVersion": "1.1",
  "component": {
    "group": "org.purpurmc.purpur",
    "module": "purpur-api",
    "version": "26.1-R0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "io.papermc.paperweight.main-capability": "org.purpurmc.purpur:purpur-api:26.1-R0.1-SNAPSHOT",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-jre"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.8"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.15"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.24.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "com.mojang",
          "module": "brigadier",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "net.md-5",
          "module": "bungeecord-chat",
          "version": {
            "requires": "1.21-R0.2-deprecated+build.21"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava"
            }
          ]
        },
        {
          "group": "org.apache.maven",
          "module": "maven-resolver-provider",
          "version": {
            "requires": "3.9.6"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.26.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-api"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-logger-slf4j"
        },
        {
          "group": "org.checkerframework",
          "module": "checker-qual",
          "version": {
            "requires": "3.49.2"
          }
        }
      ],
      "files": [
        {
          "name": "purpur-api-26.1-R0.1-SNAPSHOT.jar",
          "url": "purpur-api-26.1-R0.1-SNAPSHOT.jar",
          "size": 2856092,
          "sha512": "1cfe9330a7bdc78b6be6414eb0ae28088144a0caf8ec46e742e5ad4d0e7080b83d8797dd90740d8a921b33b7e00c419bb32da9619223e9395a7b66e7a5e04917",
          "sha256": "b6bed169c7a3fc8db03e2a2d9920e963e21c7ddb48d6ebc412d04c71aae07965",
          "sha1": "b86f4505dcee86e7e78a4c0d2302902440424647",
          "md5": "e5d9d30a2ed8700293b1be9be53ec6d2"
        }
      ],
      "capabilities": [
        {
          "group": "org.purpurmc.purpur",
          "name": "purpur-api",
          "version": "26.1-R0.1-SNAPSHOT"
        },
        {
          "group": "org.bukkit",
          "name": "bukkit",
          "version": "26.1-R0.1-SNAPSHOT"
        },
        {
          "group": "io.papermc.paper",
          "name": "paper-mojangapi",
          "version": "26.1-R0.1-SNAPSHOT"
        },
        {
          "group": "org.spigotmc",
          "name": "spigot-api",
          "version": "26.1-R0.1-SNAPSHOT"
        },
        {
          "group": "com.destroystokyo.paper",
          "name": "paper-api",
          "version": "26.1-R0.1-SNAPSHOT"
        },
        {
          "group": "com.destroystokyo.paper",
          "name": "paper-mojangapi",
          "version": "26.1-R0.1-SNAPSHOT"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "io.papermc.paperweight.main-capability": "org.purpurmc.purpur:purpur-api:26.1-R0.1-SNAPSHOT",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.maven.resolver",
          "module": "maven-resolver-connector-basic",
          "version": {
            "requires": "1.9.18"
          }
        },
        {
          "group": "org.apache.maven.resolver",
          "module": "maven-resolver-transport-http",
          "version": {
            "requires": "1.9.18"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-jre"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.joml",
          "module": "joml",
          "version": {
            "requires": "1.10.8"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.5.15"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.24.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.16"
          }
        },
        {
          "group": "com.mojang",
          "module": "brigadier",
          "version": {
            "requires": "1.3.10"
          }
        },
        {
          "group": "net.md-5",
          "module": "bungeecord-chat",
          "version": {
            "requires": "1.21-R0.2-deprecated+build.21"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava"
            }
          ]
        },
        {
          "group": "org.apache.maven",
          "module": "maven-resolver-provider",
          "version": {
            "requires": "3.9.6"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "net.kyori",
          "module": "adventure-bom",
          "version": {
            "requires": "4.26.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "net.kyori",
          "module": "adventure-api"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-minimessage"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-gson"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-legacy"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-serializer-plain"
        },
        {
          "group": "net.kyori",
          "module": "adventure-text-logger-slf4j"
        }
      ],
      "files": [
        {
          "name": "purpur-api-26.1-R0.1-SNAPSHOT.jar",
          "url": "purpur-api-26.1-R0.1-SNAPSHOT.jar",
          "size": 2856092,
          "sha512": "1cfe9330a7bdc78b6be6414eb0ae28088144a0caf8ec46e742e5ad4d0e7080b83d8797dd90740d8a921b33b7e00c419bb32da9619223e9395a7b66e7a5e04917",
          "sha256": "b6bed169c7a3fc8db03e2a2d9920e963e21c7ddb48d6ebc412d04c71aae07965",
          "sha1": "b86f4505dcee86e7e78a4c0d2302902440424647",
          "md5": "e5d9d30a2ed8700293b1be9be53ec6d2"
        }
      ],
      "capabilities": [
        {
          "group": "org.purpurmc.purpur",
          "name": "purpur-api",
          "version": "26.1-R0.1-SNAPSHOT"
        },
        {
          "group": "org.bukkit",
          "name": "bukkit",
          "version": "26.1-R0.1-SNAPSHOT"
        },
        {
          "group": "io.papermc.paper",
          "name": "paper-mojangapi",
          "version": "26.1-R0.1-SNAPSHOT"
        },
        {
          "group": "org.spigotmc",
          "name": "spigot-api",
          "version": "26.1-R0.1-SNAPSHOT"
        },
        {
          "group": "com.destroystokyo.paper",
          "name": "paper-api",
          "version": "26.1-R0.1-SNAPSHOT"
        },
        {
          "group": "com.destroystokyo.paper",
          "name": "paper-mojangapi",
          "version": "26.1-R0.1-SNAPSHOT"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "io.papermc.paperweight.main-capability": "org.purpurmc.purpur:purpur-api:26.1-R0.1-SNAPSHOT",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "purpur-api-26.1-R0.1-SNAPSHOT-sources.jar",
          "url": "purpur-api-26.1-R0.1-SNAPSHOT-sources.jar",
          "size": 2056218,
          "sha512": "384a419215bffc375666beef5ef571619c74e239dce6f45ee9a968cbd6b490935b167089093451397f9428deab66c23682f7a9d10622fdf93b94779624506fbc",
          "sha256": "9b7f87cc41627ac8e128074f3be1c16892a72fe2f4cfabc01eaaf8677d1b812f",
          "sha1": "64e3726359179ff68cb954b11167753ffd9a71ea",
          "md5": "5a9fc634928d8494cff2a7150092bafd"
        }
      ],
      "capabilities": [
        {
          "group": "org.purpurmc.purpur",
          "name": "purpur-api",
          "version": "26.1-R0.1-SNAPSHOT"
        },
        {
          "group": "org.bukkit",
          "name": "bukkit",
          "version": "26.1-R0.1-SNAPSHOT"
        },
        {
          "group": "io.papermc.paper",
          "name": "paper-mojangapi",
          "version": "26.1-R0.1-SNAPSHOT"
        },
        {
          "group": "org.spigotmc",
          "name": "spigot-api",
          "version": "26.1-R0.1-SNAPSHOT"
        },
        {
          "group": "com.destroystokyo.paper",
          "name": "paper-api",
          "version": "26.1-R0.1-SNAPSHOT"
        },
        {
          "group": "com.destroystokyo.paper",
          "name": "paper-mojangapi",
          "version": "26.1-R0.1-SNAPSHOT"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "io.papermc.paperweight.main-capability": "org.purpurmc.purpur:purpur-api:26.1-R0.1-SNAPSHOT",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "purpur-api-26.1-R0.1-SNAPSHOT-javadoc.jar",
          "url": "purpur-api-26.1-R0.1-SNAPSHOT-javadoc.jar",
          "size": 22207865,
          "sha512": "1027830e7fc198e5d95de7d650cf5c214a09f70f44c98b683bbb6eb74bc843bdf77935fe6846aafd806f64cd5e27e58352b3abbeda97e4e16b4cc7e597a0c36b",
          "sha256": "c696bc9ecd132a0871e4c5b3ea7dd5d5223490ad15e9c1ee195187ebb8afb9fd",
          "sha1": "5329b9e537548c97c2c4a9f256150ade57ed082f",
          "md5": "3b3e1c29222090a24dbe6845f542ec11"
        }
      ],
      "capabilities": [
        {
          "group": "org.purpurmc.purpur",
          "name": "purpur-api",
          "version": "26.1-R0.1-SNAPSHOT"
        },
        {
          "group": "org.bukkit",
          "name": "bukkit",
          "version": "26.1-R0.1-SNAPSHOT"
        },
        {
          "group": "io.papermc.paper",
          "name": "paper-mojangapi",
          "version": "26.1-R0.1-SNAPSHOT"
        },
        {
          "group": "org.spigotmc",
          "name": "spigot-api",
          "version": "26.1-R0.1-SNAPSHOT"
        },
        {
          "group": "com.destroystokyo.paper",
          "name": "paper-api",
          "version": "26.1-R0.1-SNAPSHOT"
        },
        {
          "group": "com.destroystokyo.paper",
          "name": "paper-mojangapi",
          "version": "26.1-R0.1-SNAPSHOT"
        }
      ]
    }
  ]
}
