name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 25
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          gradle-version: current

      - name: Build with Gradle
        run: ./gradlew build --continue
        continue-on-error: true

      - name: Upload built JAR
        uses: actions/upload-artifact@v7
        with:
          name: levelborder-artifacts
          path: build/libs